# 80-launcher-desktop.sh
# Sourced by install.sh. Step 9b/10 (desktop half): the classic-mode desktop+
# OpenHands/browser-chat-UI launcher generator (build_desktop_launcher) and
# the kilo-mode launcher installer (build_kilo_launcher). The script generator
# itself is in 80-launcher-build.sh (build_start_script) and the launch-and-
# verify flow in 80-launcher-verify.sh (launch_and_verify, launch_and_verify_
# kilo, run_launcher_step).

# --- Step 9b: desktop icon that opens start-local-llama.sh in its own ---
# --- terminal window, so starting the model is a single double-click. ---
# Also offers, every time the icon is used to actually start the server (not
# on the "already running" fast path), to install/launch OpenHands - a
# dockerless pip-based AI coding agent CLI (https://docs.openhands.dev/) -
# inside the same $CONTAINER_NAME, pointed at this project's local litellm
# proxy, AND to enable llama.cpp's own browser chat UI on the server it's
# about to start. Both kept out of the model-only fast path (the "already
# running, exit 0" branch below) on purpose: that path is for "I just need
# the server up", not "open/enable something extra" - and if the server is
# already running, its --no-webui choice was already locked in when it
# started, so there's nothing left to toggle without a restart.
build_desktop_launcher() {
  if [ "$INSTALL_MODE" != "classic" ]; then
    log "Skipping classic OpenHands/browser-chat-ui launcher (mode is $INSTALL_MODE)"
    return
  fi
  if [ "$INSTALL_DESKTOP_SHORTCUT" = "yes" ]; then
    # start-openhands.sh: install (first run only) + launch OpenHands inside
    # $CONTAINER_NAME, auto-pointed at this project's proxy - same endpoint
    # (http://localhost:$PROXY_PORT/v1) and wildcard "openai/local-llm"
    # model string README.md documents for Zoo Code/Continue/other OpenAI-
    # Compatible clients, so re-running install.sh and switching model
    # profiles never requires touching this either.
    #
    # Dockerless CLI (`pip install openhands`, command `openhands`), not the
    # Docker-based web UI variant - keeps everything inside the one
    # container this project already uses, no nested container/daemon on an
    # immutable host. Requires Python 3.12 specifically (OpenHands' own
    # requirement, confirmed against its PyPI metadata 2026-08-03, not this
    # project's choice) - installed via dnf if the container doesn't have it.
    # LLM_* env vars + --override-with-envs is OpenHands' own documented
    # non-interactive LLM config path, so this never needs its interactive
    # first-run setup wizard.
    cat > "$BIN_DIR/start-openhands.sh" << EOF
#!/usr/bin/env bash
# start-openhands.sh
# Generated by install.sh - re-run install.sh to change any of these
# settings, don't hand-edit (your edits won't survive the next install.sh
# run). Installs OpenHands (https://docs.openhands.dev/, the dockerless pip
# CLI, not the Docker-based web UI) inside $CONTAINER_NAME the first time
# it's needed - skipped on every later run once \`command -v openhands\`
# succeeds - then launches it pointed at this project's local proxy at
# http://localhost:$PROXY_PORT/v1 so it talks to your local model with no
# manual setup, same one-stable-endpoint pattern README.md documents for
# Zoo Code/Continue.

LOG_FILE="\$HOME/.local/state/openhands-install.log"
mkdir -p "\$(dirname "\$LOG_FILE")"

if ! distrobox enter "$CONTAINER_NAME" -- bash -lc 'command -v openhands' >/dev/null 2>&1; then
  echo "OpenHands not found inside $CONTAINER_NAME - installing (needs Python 3.12, can take a few minutes)..."
  distrobox enter "$CONTAINER_NAME" -- bash -lc '
    set -e
    if command -v python3.12 >/dev/null 2>&1; then
      PY=python3.12
    elif python3 --version 2>&1 | grep -q "3\.12"; then
      PY=python3
    else
      echo "Python 3.12 not found - installing via dnf..." >&2
      sudo dnf install -y python3.12
      PY=python3.12
    fi
    if ! "\$PY" -m pip --version >/dev/null 2>&1; then
      # Fedora does not ship a per-minor-version "python3.12-pip" dnf
      # package (confirmed against this project'"'"'s own Fedora Distrobox
      # image, which errored "No match for argument: python3.12-pip"), and
      # the version dnf'"'"'s plain "python3-pip" happens to target won'"'"'t
      # necessarily match \$PY. ensurepip is a stdlib module bundled with
      # every CPython 3.4+ build, so it installs pip for this exact
      # interpreter regardless of distro packaging.
      echo "pip module not found for \$PY - bootstrapping via ensurepip..." >&2
      sudo "\$PY" -m ensurepip --upgrade
    fi
    # Plain pip cannot resolve openhands'"'"' dependency tree (confirmed:
    # pip backtracks through hundreds of browser-use/opentelemetry/
    # huggingface-hub versions and still fails with ResolutionImpossible on
    # openhands-sdk vs lmnr, even though a valid resolution exists). openhands'"'"'
    # own PyPI page recommends uv for exactly this reason - its resolver
    # handles the same dependency set cleanly (verified: uv pip install
    # openhands resolves and runs with no changes needed on either side).
    if ! "\$PY" -m uv --version >/dev/null 2>&1; then
      sudo "\$PY" -m pip install --break-system-packages -q uv
    fi
    sudo "\$PY" -m uv pip install --python "\$PY" --break-system-packages -q openhands
  ' 2>&1 | tee -a "\$LOG_FILE"
  # \$PIPESTATUS[0] is the distrobox/install command's own exit code - tee
  # itself always succeeds, so testing the pipeline's own \$? would silently
  # hide a failed install (this bit OpenHands before: python3.12 lacked its
  # pip module, the install died, but tee'"'"'s success made the script claim
  # "OpenHands installed." anyway).
  if [ "\${PIPESTATUS[0]}" -ne 0 ]; then
    echo "OpenHands install failed - see \$LOG_FILE for the full log. Not launching it." >&2
    exit 1
  fi
  echo "OpenHands installed."
fi

echo "Launching OpenHands against http://localhost:$PROXY_PORT/v1 (this project's local proxy)..."
distrobox enter "$CONTAINER_NAME" -- bash -lc "LLM_MODEL='openai/local-llm' LLM_BASE_URL='http://localhost:$PROXY_PORT/v1' LLM_API_KEY='$PROXY_MASTER_KEY' openhands --override-with-envs"
EOF
    chmod +x "$BIN_DIR/start-openhands.sh"

    # model-session.sh: runs inside the terminal window the desktop icon
    # opens. A plain script file rather than more inline shell packed into
    # the icon's own bash -c string below - once that string has to both
    # prompt for OpenHands AND conditionally open a second terminal for it,
    # the quoting nests too deeply to keep readable/correct inline.
    cat > "$BIN_DIR/model-session.sh" << EOF
#!/usr/bin/env bash
# model-session.sh
# Generated by install.sh - re-run install.sh to change any of these
# settings, don't hand-edit (your edits won't survive the next install.sh
# run). Runs inside the terminal window the "Start Local Model" desktop icon
# opens: offers to also install/launch OpenHands (in a second terminal
# window, so both stay visible) and/or enable llama.cpp's own browser chat
# UI, then runs start-local-llama.sh in this one so its own log output stays
# visible.

TERMINAL_CMD=""
if command -v konsole >/dev/null 2>&1; then
  TERMINAL_CMD="konsole -e"
elif command -v gnome-terminal >/dev/null 2>&1; then
  TERMINAL_CMD="gnome-terminal --"
elif command -v xterm >/dev/null 2>&1; then
  TERMINAL_CMD="xterm -e"
fi

read -rp "Also install/launch OpenHands (AI coding agent) in $CONTAINER_NAME? [y/N] " OH_ANS
if [[ "\$OH_ANS" =~ ^[Yy] ]]; then
  if [ -n "\$TERMINAL_CMD" ]; then
    \$TERMINAL_CMD bash -c "$BIN_DIR/start-openhands.sh; echo; echo 'OpenHands exited.'; read -p 'Press Enter to close this window.'" &
    disown
  else
    echo "No terminal emulator found to open OpenHands in its own window - running it here instead, before llama-server."
    "$BIN_DIR/start-openhands.sh"
  fi
fi

# Same server process, same port, same model already in VRAM either way -
# this just toggles whether llama.cpp also serves its own browser chat UI
# alongside the API, so it never loads a second copy of the model.
read -rp "Also enable llama.cpp's browser chat UI on this server (http://127.0.0.1:$LLAMA_PORT)? [y/N] " WEBUI_ANS
if [[ "\$WEBUI_ANS" =~ ^[Yy] ]]; then
  export LLAMA_ENABLE_WEBUI=yes
fi

"$BIN_DIR/start-local-llama.sh"
echo
echo "llama-server exited."
read -rp "Press Enter to close this window. " _
EOF
    chmod +x "$BIN_DIR/model-session.sh"

    cat > "$BIN_DIR/start-local-llama-desktop.sh" << EOF
#!/usr/bin/env bash
# start-local-llama-desktop.sh
# Generated by install.sh. Double-click target for the "Start Local Model"
# desktop icon: opens model-session.sh (offers OpenHands, then runs
# start-local-llama.sh) in its own terminal window so you can watch it while
# you work, without typing anything by hand. Falls back to a copy-paste
# notification if no terminal emulator can be found.

if curl -s -o /dev/null "http://localhost:$LLAMA_PORT/health"; then
  notify-send "Local model" "llama-server is already running at http://localhost:$LLAMA_PORT"
  exit 0
fi

TERMINAL_CMD=""
if command -v konsole >/dev/null 2>&1; then
  TERMINAL_CMD="konsole -e"
elif command -v gnome-terminal >/dev/null 2>&1; then
  TERMINAL_CMD="gnome-terminal --"
elif command -v xterm >/dev/null 2>&1; then
  TERMINAL_CMD="xterm -e"
fi

if [ -z "\$TERMINAL_CMD" ]; then
  notify-send -u critical "Local model: no terminal emulator found" \\
    "Paste this into a terminal yourself: $BIN_DIR/model-session.sh"
  exit 1
fi

\$TERMINAL_CMD bash -c "$BIN_DIR/model-session.sh" &
disown
notify-send "Local model" "Starting llama-server in a new terminal window..."
EOF
    chmod +x "$BIN_DIR/start-local-llama-desktop.sh"

    cat > "$DESKTOP_DIR/claude-local-start-model.desktop" << EOF
[Desktop Entry]
Type=Application
Name=Start Local Model
Comment=Launch llama-server for Claude Code local mode (offers OpenHands too) in its own terminal window
Exec=$BIN_DIR/start-local-llama-desktop.sh
Icon=media-playback-start
Terminal=false
Categories=Utility;
EOF
    chmod +x "$DESKTOP_DIR/claude-local-start-model.desktop"
    log "Generated $BIN_DIR/start-openhands.sh, $BIN_DIR/model-session.sh, $BIN_DIR/start-local-llama-desktop.sh and its desktop icon"
    echo "Desktop icon 'Start Local Model' installed - double-click it to launch"
    echo "llama-server in its own terminal window (falls back to a copy-paste"
    echo "notification if no terminal emulator is found; not yet verified on"
    echo "your specific desktop session, check that it actually pops a window)."
    echo "It also now asks whether to install/launch OpenHands (an AI coding"
    echo "agent CLI) inside $CONTAINER_NAME, pointed at this project's local"
    echo "proxy, and whether to enable llama.cpp's own browser chat UI on the"
    echo "server - answer 'n' (or just press Enter) to skip either and get the"
    echo "old model-only behavior."
  fi
}

# --- Kilo mode: start-local-model.sh + its desktop icon ---
# The desktop-icon flow for kilo mode. Installs the checked-in start-local-
# model.sh template (which reads its config from CONF_FILE at runtime) plus a
# terminal wrapper and desktop entry. The template does the whole
# scan-offer-start-test-sync loop the Kilo Code provider needs, and doubles as
# the install-time test flow (run with --profile <stem>). Every runtime is
# handled: llama.cpp (flags built at runtime by sourcing the matched profile -
# the same profile generator install.d uses), ollama (serve + run), vllm
# (serve). The model entry in the KILO config is rewritten by
# sync-local-model.sh (installed by install.d/85-kilo-sync.sh) after every
# successful start, so Kilo Code always sees only the currently-running model.
build_kilo_launcher() {
  if [ "$INSTALL_MODE" != "kilo" ]; then
    log "Skipping kilo launcher installation (mode is $INSTALL_MODE)"
    return
  fi
  mkdir -p "$BIN_DIR" "$KILO_STATE_DIR"
  cp "$SCRIPT_DIR/templates/bin/start-local-model.sh" "$BIN_DIR/start-local-model.sh"
  cp "$SCRIPT_DIR/templates/bin/start-local-model-lib.sh" "$BIN_DIR/start-local-model-lib.sh"
  chmod +x "$BIN_DIR/start-local-model.sh"
  log "Installed $BIN_DIR/start-local-model.sh + start-local-model-lib.sh (from repo templates)"

  if [ "$INSTALL_DESKTOP_SHORTCUT" = "yes" ]; then
    cp "$SCRIPT_DIR/templates/bin/start-local-model-desktop.sh" "$BIN_DIR/start-local-model-desktop.sh"
    chmod +x "$BIN_DIR/start-local-model-desktop.sh"
    mkdir -p "$DESKTOP_DIR"
    # The .desktop Exec line needs the concrete path (desktop launchers can't
    # read the config), so the __BIN_DIR__ token is sed-baked here.
    sed "s|__BIN_DIR__|$BIN_DIR|g" "$SCRIPT_DIR/templates/desktop/local-model.desktop" > "$DESKTOP_DIR/local-model.desktop"
    chmod +x "$DESKTOP_DIR/local-model.desktop"
    log "Installed $BIN_DIR/start-local-model-desktop.sh and $DESKTOP_DIR/local-model.desktop"
    echo "Desktop icon 'Start Local Model (Kilo)' installed - double-click it to"
    echo "open the model picker in a terminal window. On KDE Plasma (Bazzite"
    echo "default), the first double-click may prompt to trust/execute it."
  fi
}